services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: react_flask_backend

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: react_flask_frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

